tasks:
  - name: Compile JavaScript
    init: make deps
    command: make generate-dev
  - name: Docker
    command: docker compose up
  - name: Fleet serve
    before: make
    init: build/fleet preparedb --dev
    command: build/fleet serve --dev
